#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexLabs.Web.TablePager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 3 "..\..\TablePager.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 4 "..\..\TablePager.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\TablePager.cshtml"
    using PagedList;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public static class TablePager
    {
        
        #line 5 "..\..\TablePager.cshtml"

    public static HelperResult Pager<T>(IPagedList<T> pagedList, String label = "Page: ")
    {
        if (pagedList.PageCount == 0) {
            return null;
        }
        var model = new PagedListData(pagedList.PageNumber, pagedList.PageSize, pagedList.PageCount, pagedList.TotalItemCount);
        return Pager(model, label);
    }

        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Pager(PagedListData model, String label) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 15 "..\..\TablePager.cshtml"
                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"float-right\">\r\n        <label>");



#line 17 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n        <ul>\r\n");



#line 19 "..\..\TablePager.cshtml"
         if (!model.CanSeeFirstPage()) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <li>\r\n                <button type=\"submit\" name=\"page\" value=\"1\">1</" +
"button>.\r\n            </li>\r\n");



#line 23 "..\..\TablePager.cshtml"
        }

#line default
#line hidden



#line 24 "..\..\TablePager.cshtml"
         foreach (var page in model.PageRange) {
            if (page == model.PageNumber) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>");



#line 26 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 27 "..\..\TablePager.cshtml"
            } else {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li><button type=\"submit\" name=\"page\" value=\"");



#line 28 "..\..\TablePager.cshtml"
                  WebViewPage.WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 28 "..\..\TablePager.cshtml"
                         WebViewPage.WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</button></li>\r\n");



#line 29 "..\..\TablePager.cshtml"
            }
        }

#line default
#line hidden



#line 31 "..\..\TablePager.cshtml"
         if (!model.CanSeeLastPage()) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <li><button type=\"submit\" name=\"page\" value=\"");



#line 32 "..\..\TablePager.cshtml"
              WebViewPage.WriteTo(@__razor_helper_writer, model.PageCount);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 32 "..\..\TablePager.cshtml"
                                WebViewPage.WriteTo(@__razor_helper_writer, model.PageCount);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</button></li>\r\n");



#line 33 "..\..\TablePager.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </div>\r\n");



#line 36 "..\..\TablePager.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult PageSizer(System.Web.Mvc.HtmlHelper html, String label = "Page Size:", Int32[] pageSizes = null) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 38 "..\..\TablePager.cshtml"
                                                                                                          
    
#line default
#line hidden


#line 39 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Label("PageSize", label));

#line default
#line hidden


#line 39 "..\..\TablePager.cshtml"
                                  
    
#line default
#line hidden


#line 40 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.DropDownList("PageSize", TableModel.GetPageSizes(pageSizes), new { onchange = "$(this).closest('form').submit();" }));

#line default
#line hidden


#line 40 "..\..\TablePager.cshtml"
                                                                                                                              
    
#line default
#line hidden


#line 41 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.ValidationMessage("PageSize"));

#line default
#line hidden


#line 41 "..\..\TablePager.cshtml"
                                       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Header(IEnumerable<TableHeader> headers) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 44 "..\..\TablePager.cshtml"
                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <thead>\r\n");



#line 46 "..\..\TablePager.cshtml"
         foreach (var header in headers) { 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <th class=\"");



#line 47 "..\..\TablePager.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, header.CssClass);

#line default
#line hidden



#line 47 "..\..\TablePager.cshtml"
                                       WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");

#line default
#line hidden


#line 47 "..\..\TablePager.cshtml"
                                          if(header.Value != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <button type=\"submit\" name=\"changeSort\" value=\"");



#line 47 "..\..\TablePager.cshtml"
                                                                         WebViewPage.WriteTo(@__razor_helper_writer, header.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" title=\"");



#line 47 "..\..\TablePager.cshtml"
                                                                                               WebViewPage.WriteTo(@__razor_helper_writer, header.ToolTip);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 47 "..\..\TablePager.cshtml"
                                                                                                                WebViewPage.WriteTo(@__razor_helper_writer, header.Title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</button> ");



#line 47 "..\..\TablePager.cshtml"
                                                                                                                                                                                  } else { 
#line default
#line hidden


#line 47 "..\..\TablePager.cshtml"
                                                                                                                                                WebViewPage.WriteTo(@__razor_helper_writer, header.Title);

#line default
#line hidden


#line 47 "..\..\TablePager.cshtml"
                                                                                                                                                                                                         }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</th>\r\n");



#line 48 "..\..\TablePager.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </thead>\r\n");



#line 50 "..\..\TablePager.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult FormHidden(ITableModel model) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\TablePager.cshtml"
                                       
    
#line default
#line hidden



#line 53 "..\..\TablePager.cshtml"
                                                                                                                                                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" name=\"SortBy\" value=\"");



#line 54 "..\..\TablePager.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, model.SortBy);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" name=\"SortAsc\" value=\"");



#line 55 "..\..\TablePager.cshtml"
    WebViewPage.WriteTo(@__razor_helper_writer, model.SortAsc.ToString());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 56 "..\..\TablePager.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
